SECRET_KEY = ''
DATABASE_ENGINE = ''
DATABASE_NAME = ''
DATABASE_USER = ''
DATABASE_PASSWORD = ''
DATABASE_HOST = ''
DATABASE_PORT = ''

EMAIL_HOST = ''
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD = ''
EMAIL_PORT = ''
DEFAULT_FROM_EMAIL = ''
SERVER_EMAIL = ''

MEDIA_URL = ''
ADMIN_MEDIA_PREFIX = ''

